version: '3.5'

services: 
  postgresql:
    image: postgres
    container_name: postgres-node
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=node,node_test
    volumes:
    - postgres-data-node:/var/lib/postgresql/data/
    ports:
    - 0.0.0.0:5432:5432
  mongodb:
    image: mongo
    container_name: mongodb-node
    environment:
      MONGO_INITDB_DATABASE: node
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata-node:/data/db
    ports:
    - 0.0.0.0:27017:27017
    command: '--wiredTigerCacheSizeGB 1.5'

volumes:
  postgres-data-node:
  postgres-data-node-test:
  mongodbdata-node: